creation de l'index des formations
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #10
Opened 2023-04-25 18:37 UTC by Mikazian

2023-04-25 19:59 UTC, No3ml3 submitted a review, later dismissed

2023-04-26 08:24 UTC, sblondeau reviewed
Simplifie ! tu fais trop de choses d'un coup !

2023-04-26 08:24 UTC, sblondeau commented on public/assets/images/reunion-reflexion.jpg
12Mo !!!

2023-04-26 08:24 UTC, sblondeau commented on src/Controller/TrainingController.php
> +        $sectors = $trainingManager->selectSector();
pas de sectors pour le moment

2023-04-26 08:24 UTC, sblondeau commented on src/Model/TrainingManager.php
> +    public function selectSector(): array
sera à mettre plus tard dans un sectorManager

2023-04-26 08:24 UTC, sblondeau commented on src/Model/TrainingManager.php
> +        JOIN sector s ON s.id = t.sector_id
pas besoin de la jointure pour l'instant

2023-04-26 08:24 UTC, sblondeau commented on src/View/Training/index.html.twig
> +						{% endif %}
affichage juste des formations dans des cards, sans classement par secteur

2023-04-26 12:14 UTC, No3ml3 submitted a review, later dismissed

2023-04-26 12:55 UTC, sblondeau requested changes
c'est bien mieux, ça se relit vite ;)(-

2023-04-26 12:55 UTC, sblondeau commented on src/.DS_Store
ouch, un DS_Store ! c'est tjs pas dans le gitignore ?

2023-04-26 12:55 UTC, sblondeau commented on src/Model/TrainingManager.php
> +        $query = "SELECT name, stage_duration FROM training";
SELECT * FROM training direct non ? 
en fait là tu anticipes sur la suivante, mais le selectAll() dans l'abstractManager est suffisant.
Tu peux laisser comme ça

2023-04-26 12:55 UTC, sblondeau commented on src/View/Training/index.html.twig
> +							<p>Durée : X ans /
c'est quoi le X ?

2023-04-26 13:25 UTC, No3ml3 submitted a review, later dismissed

2023-04-26 14:33 UTC, sblondeau approved these changes

2023-04-26 15:24 UTC, No3ml3 approved these changes

2023-04-26 15:36 UTC, merged