home_page
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #16
Opened 2023-04-28 08:35 UTC by MZL95

2023-04-28 08:35 UTC, No3ml3 submitted a review, later dismissed

2023-04-28 09:04 UTC, sblondeau requested changes

2023-04-28 09:04 UTC, sblondeau commented on public/assets/images/etudiANTE.png
image BEAUCOUP trop grosse, pas plus de 100ko

2023-04-28 09:04 UTC, sblondeau commented on public/assets/images/etudiANTE.png
mais en fait j'ai pas l'impression que tu t'en sert ? donc supprime la

2023-04-28 09:04 UTC, sblondeau commented on public/assets/images/event_480.jpg
et celle ci tu la renomme en placeholder_event.jpg 
elle te servira de placeholder si tes events ont pas d'image, et si tu as le temps d'implementer l'upload sur les events, tu pourras la remplacer par l'image de l'event en cours

2023-04-28 09:04 UTC, sblondeau commented on database.sql
> +VALUES ("Journée Porte ouverte", "Le samedi 10 mai 2023, le lycée vous ouvre ses portes de 9h à 17h !
ajoute en au moins un second en base de données, histoire de tester que tout fonctionne bien au niveau de ta requete SQL qui doit recup le dernier

2023-04-28 11:35 UTC, Mikazian submitted a review, later dismissed

2023-04-28 14:17 UTC, sblondeau requested changes

2023-04-28 14:17 UTC, sblondeau commented on public/assets/images/etudiANTE.png
enlève cette image

2023-04-28 14:17 UTC, sblondeau requested changes

2023-04-28 14:46 UTC, MZL95 commented on public/assets/images/etudiANTE.png
normalement c'est bon la

2023-05-01 20:30 UTC, sblondeau approved these changes

2023-05-02 09:24 UTC, Mikazian approved these changes

2023-05-02 10:29 UTC, merged