S03 us29 admin equipe affichage
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #19
Opened 2023-04-28 11:56 UTC by No3ml3

2023-04-28 14:19 UTC, sblondeau requested changes

2023-04-28 14:19 UTC, sblondeau commented on src/View/Admin/employee/index.html.twig
> +										<a href="updateEmployee?id=">Modifier</a>
non ! pas de balise a à l'intérieur d'un button ! avec pico, tu fait `<a href="" role="button>`

2023-04-28 14:19 UTC, sblondeau commented on src/View/Admin/employee/index.html.twig
> +										<a href="deleteEmployee?id=">Supprimer</a>
et pour la suppression, c'est pas un lien mais un form (et donc une balise button :D )
pour aller au plus vite, tu peux aussi enlever le bouton là et rajouter le form sur l'US de la suppression

2023-05-02 09:33 UTC, Mikazian commented on public/assets/css/Admin/employee/employeeIndex.css
> +    margin-top: 0.5rem;
var(--spacing)

2023-05-02 09:33 UTC, Mikazian commented on public/assets/css/Admin/employee/employeeIndex.css
> +    margin-bottom: 0.5rem;
var(--spacing)

2023-05-02 09:39 UTC, Mikazian submitted a review, later dismissed

2023-05-02 10:31 UTC, sblondeau submitted a review, later dismissed

2023-05-02 13:47 UTC, merged