Init
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #2
Opened 2023-04-12 14:20 UTC by No3ml3

2023-04-12 15:18 UTC, sblondeau requested changes

2023-04-12 15:18 UTC, sblondeau commented on public/assets/css/style.css
> +:root{
-  manque le chargement de picocss
-  il faut forcer le data-theme="light" sur la balise html
-  il faut pas utliliser le sélecteur :root directement pour les couleurs (voir la doc de pico partie custom, ou mon repo de live coding)
-  mettre "Lycée Jeannette Verdier" dans le title sur le layout

2023-04-13 09:52 UTC, Zakari-B commented on src/View/layout.html.twig
> +    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@1.*/css/pico.min.css" />
Il sort d'où ce lien de CDN ..? Ce n'est pas celui de la doc.

2023-04-13 12:42 UTC, Zakari-B approved these changes

2023-04-13 12:42 UTC, merged