S04 us08 nore lycee
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #26
Opened 2023-05-02 08:46 UTC by No3ml3

2023-05-02 09:41 UTC, Mikazian approved these changes

2023-05-02 14:00 UTC, Zakari-B commented on src/View/Admin/employee/index.html.twig
J'ai bien l'impression que ça devrait être dans une autre US ça. Pourquoi de la gestion de personnel dans "notre lycée" ?

2023-05-03 21:46 UTC, Mikazian submitted a review, later dismissed

2023-05-04 07:19 UTC, sblondeau requested changes

2023-05-04 07:29 UTC, Mikazian approved these changes

2023-05-04 08:32 UTC, sblondeau submitted a review, later dismissed

2023-05-04 08:44 UTC, merged