S04 us15 competences formation
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #30
Opened 2023-05-03 15:30 UTC by Mikazian

2023-05-03 16:08 UTC, No3ml3 submitted a review, later dismissed

2023-05-03 20:26 UTC, sblondeau requested changes

2023-05-03 20:26 UTC, sblondeau commented on database.sql
> +CREATE TABLE EVENT(ID
event (en minuscule)

2023-05-03 20:26 UTC, sblondeau commented on database.sql
> +CREATE TABLE EVENT(ID
id aussi

2023-05-04 08:48 UTC, sblondeau approved these changes

2023-05-04 08:48 UTC, merged