S02 us01 navbar
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #4
Opened 2023-04-17 18:29 UTC by Mikazian

2023-04-18 09:21 UTC, No3ml3 approved these changes

2023-04-18 09:58 UTC, sblondeau requested changes

2023-04-18 09:58 UTC, sblondeau commented on public/.DS_Store
dstore versionné,
il faut le retirer avec un git rm --cached public/.DS_Store

2023-04-18 09:58 UTC, sblondeau commented on public/assets/.DS_Store
idem

2023-04-18 09:58 UTC, sblondeau commented on database.sql
ce fichier ne devrait pas se trouver modifié dans ta PR

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +h2, h3, h4, h5, h6 {
tu as vraiment besoin de modif les h2 à h6 pour un navbar.css ?

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +[role="button"], button, input[type="button"], input[type="reset"], input[type="submit"] {
si c'est le style voulu pour tout le site, met le dans le fichier style.css pltutot ?

2023-04-18 09:58 UTC, sblondeau commented on src/.DS_Store
idem

2023-04-18 09:58 UTC, sblondeau commented on src/View/Components/_navbar.html.twig
> +<script src="script.js"></script></body></html>
pb d'indentation ?

2023-04-18 09:58 UTC, sblondeau commented on src/View/Home/index.html.twig
> +	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus odio delectus explicabo aut aliquam necessitatibus optio totam laudantium. Consectetur minus, cupiditate perferendis facilis
je ne veux pas de ces lorem ipsum, ok pour que tu fasses des tests mais faut pas le push

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +
ta la meme chose dans les 2 media query ? une seule suffit je pense

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +        height: calc(100vh - 30vh - 68px); /* 100vh - header - (navbar + border-bottom) */
pas de code commenté

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +}
idem, inutile je pense
ton CSS est très compliqué pour juste une navbar

2023-04-18 09:58 UTC, sblondeau commented on public/assets/css/navbar.css
> +h2, h3, h4, h5, h6 {
devrait plus etre dans style.css ?

2023-04-19 08:22 UTC, No3ml3 approved these changes

2023-04-19 08:34 UTC, sblondeau approved these changes

2023-04-19 08:34 UTC, merged