S05 us45 add training
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #52
Opened 2023-05-07 14:05 UTC by Mikazian

2023-05-08 11:04 UTC, No3ml3 approved these changes

2023-05-08 12:21 UTC, sblondeau requested changes

2023-05-08 12:21 UTC, sblondeau commented on src/Controller/AdminTrainingController.php
> +        $maxLenght = 255;
lentgTH pas gHT

2023-05-08 12:21 UTC, sblondeau commented on src/Controller/AdminTrainingController.php
> +        if (empty($training['nb_students'])) {
check que c'est > 0 aussi

2023-05-08 12:21 UTC, sblondeau commented on src/Controller/AdminTrainingController.php
> +        if (empty($training['success_rate'])) {
et > 0

2023-05-08 12:21 UTC, sblondeau commented on src/Controller/AdminTrainingController.php
> +        if (empty($training['stage_duration'])) {
et > 0

2023-05-08 13:46 UTC, Mikazian commented on src/Controller/AdminTrainingController.php
> +        if (empty($training['nb_students'])) {
Je l'avais ajouté mais grumphp me disait que j'avais trop de if du coup j'ai enlevé

2023-05-08 13:56 UTC, Mikazian commented on src/Controller/AdminTrainingController.php
> +        $maxLenght = 255;
corrigé

2023-05-08 13:57 UTC, Mikazian commented on src/Controller/AdminTrainingController.php
> +        if (empty($training['nb_students'])) {
J'ai pu rajouter qu'un seul if pour voir si c'est > 0
grumphp fesait la tête quand je mettais tout

2023-05-09 07:13 UTC, No3ml3 approved these changes

2023-05-09 07:19 UTC, sblondeau requested changes

2023-05-09 07:19 UTC, sblondeau commented on src/Controller/AdminTrainingController.php
> +        $maxLentght = 255;
gth !

2023-05-09 08:05 UTC, No3ml3 submitted a review, later dismissed

2023-05-09 08:06 UTC, sblondeau approved these changes

2023-05-09 08:45 UTC, sblondeau approved these changes

2023-05-09 08:45 UTC, merged