creation footer
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #8
Opened 2023-04-21 14:27 UTC by MZL95

2023-04-21 14:30 UTC, Mikazian submitted a review, later dismissed

2023-04-23 13:36 UTC, sblondeau requested changes
qq correction sur le CSS (couleurs)
le CSS me semble beaucoup trop chargé, media query inutile je pense, mais on va passer à autre chose là, le footer est déjà en cours depuis trop longtemps
corrige les variables ça sera déjà ça ^^

2023-04-23 13:36 UTC, sblondeau commented on public/assets/css/footer.css
> +/* footer */
2 fois meme comment

2023-04-23 13:36 UTC, sblondeau commented on public/assets/css/footer.css
> +    border-top: 1px dashed #000;
couleur en variable

2023-04-23 13:36 UTC, sblondeau commented on public/assets/css/footer.css
> +    background-color: #FFAD33;
couleur en variable

2023-04-23 13:36 UTC, sblondeau commented on public/assets/css/navbar.css
>      box-shadow: 0px 10px 10px #0000000d;
couleur

2023-04-25 07:11 UTC, Mikazian submitted a review, later dismissed

2023-04-25 07:16 UTC, sblondeau requested changes

2023-04-25 07:16 UTC, sblondeau commented on public/assets/css/footer.css
> +    --secondary: #FFAD33;
les couleurs génériques de ta charte graphique tu dois les définir dans :root du fichier de style principal afin qu'elles soient utilisables partout, tu ne dois pas les redéfinir dans chaque bloc CSS sinon ça ne sert à rien

2023-04-25 07:16 UTC, sblondeau commented on public/assets/css/footer.css
> +    --secondary: #FFAD33;
idem

2023-04-25 07:16 UTC, sblondeau commented on public/assets/css/navbar.css
>      box-shadow: 0px 10px 10px #0000000d;
tjs pas de couleur en variable css

2023-04-25 07:16 UTC, sblondeau commented on public/assets/css/style.css
>      --primary: #2E71C0;
tu vois ici que --secondary est DEJA definie en fait

2023-04-25 15:14 UTC, sblondeau approved these changes

2023-04-25 15:15 UTC, merged