la page qui affiche l'équipe
WildCodeSchool/202302-orleans-php-project2-jeanetteverdier pull request #9
Opened 2023-04-25 07:31 UTC by No3ml3

2023-04-25 08:52 UTC, Mikazian commented on public/assets/css/team.css
> +      width: clamp(300px, 3vw, 700px);
utiliser le clamp90

2023-04-25 08:52 UTC, Mikazian commented on public/assets/css/team.css
> +   box-shadow: 5px 5px 10px rgb(161, 140, 140);
utiliser ce box-shadow -> box-shadow: 0 5px 20px rgba(0, 0, 0, 0.1);

2023-04-25 08:52 UTC, Mikazian commented on public/assets/css/team.css
> +   background: rgba(255, 255, 255, 0.595);
utliser ça ici : rgba(255, 255, 255, 0.2)

2023-04-25 08:52 UTC, Mikazian commented on src/View/Pages/team.html.twig
> +	{{ parent() }}
échanger le parent et notre equipe

2023-04-25 08:52 UTC, Mikazian commented on src/routes.php
> +    'team' => ['TeamController', 'index',],
mettre notre-equipe

2023-04-25 09:01 UTC, Mikazian submitted a review, later dismissed

2023-04-25 11:00 UTC, sblondeau requested changes
attention tu confonds fausse données (pour tester) avec vrai faux site finalisé :D 
ce que je veux dire c'est que tu peux mettre 1 image de personne pour le placeholder dans assets/images
le reste seront des images uploadées par l'admin et ne seront donc pas versionnées. En gros je ne veux pas 50+ fichiers dans ta PR avec des images fakes ! au final j'aurai 6-8 fichiers, une fois nettoyé je relirai le reste ;-)

2023-04-25 14:26 UTC, Mikazian approved these changes

2023-04-25 15:42 UTC, sblondeau requested changes

2023-04-25 15:42 UTC, sblondeau commented on public/assets/css/team.css
> +   background: rgba(255, 255, 255, 0.2);
variables css pour touts les couleurs (meme dans les shadow)

2023-04-25 15:42 UTC, sblondeau commented on public/assets/css/navbar.css
>      box-shadow: 0px 10px 10px #0000000d;
couleur variable

2023-04-25 18:13 UTC, Mikazian commented on public/assets/css/style.css
> +    --clamp60: clamp(700px, 60vw, 1200px);
attention ton clamp :
--clamp60: clamp(650px, 60vw, 1200px);

2023-04-26 06:53 UTC, Mikazian approved these changes

2023-04-26 08:20 UTC, sblondeau requested changes

2023-04-26 08:20 UTC, sblondeau commented on public/assets/css/team.css
> +   color: white;
couleur en variable

2023-04-26 08:20 UTC, sblondeau commented on public/assets/css/team.css
> +   color: black;
couleur en variable (tu as d'autres endroit ou c'est pas bon, je te laisse tout rechecker)

2023-04-26 08:20 UTC, sblondeau commented on src/Model/TeamManager.php
> +class TeamManager extends AbstractManager
si je veux pinailler, le terme "team" est pas très bien choisi vu que ce sont des employés que tu as dedant, pas des équipe (donc une table employee ou team_member éventuellement ?) avec tout bien renommé...   tu peux laisser comme ça si tu veux mais fait attention pour le futur de bien nommer les choses sinon on s'y perd vite, là on a du mal à voir la différente entre une "team" et un "department"

2023-04-26 12:37 UTC, Mikazian approved these changes

2023-04-26 12:47 UTC, sblondeau approved these changes

2023-04-26 12:53 UTC, Mikazian approved these changes

2023-04-26 12:54 UTC, Mikazian approved these changes

2023-04-26 14:25 UTC, merged